openapi: 3.1.0
x-stoplight:
  id: fq41ilnaogbg3
info:
  title: Credit
  version: '1.0'
  summary: Credit
  description: Credit path
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  contact:
    name: Support
    url: 'https://www.flex.one'
    email: support@flex.one
servers:
  - url: 'https://platform.flex.one'
    description: Production
  - url: 'https://platform.flexbase.dev'
    description: Development
  - url: 'http://localhost:3000'
    description: Local
paths:
  '/credit/cards/{cardId}/transaction/authorization':
    parameters:
      - schema:
          type: string
        name: cardId
        in: path
        required: true
        description: The card identifier
    post:
      summary: Decision Approval for Credit Transaction Authorization
      tags:
        - Credit
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - approved
                properties:
                  approved:
                    type: boolean
                    x-stoplight:
                      id: kayq13jpsujhk
                  error:
                    type: object
                    x-stoplight:
                      id: 1rfg43ofv2c0w
                    required:
                      - code
                      - message
                    properties:
                      code:
                        type: string
                        x-stoplight:
                          id: 8bcf8lyiqpb0o
                      message:
                        type: string
                        x-stoplight:
                          id: y6x15fyl8zbxv
      operationId: decisionCreditTransactionAuthorization
      x-stoplight:
        id: ti9emthcb4xgr
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - amount
                - invoiceId
                - correlationId
                - personId
              properties:
                amount:
                  type: number
                  x-stoplight:
                    id: henh4bnu2457r
                invoiceId:
                  type: string
                  x-stoplight:
                    id: 24ma1gxg7i0qf
                correlationId:
                  type: string
                  x-stoplight:
                    id: xkp3btqy152ng
                personId:
                  type: string
                  x-stoplight:
                    id: k0e83afodl7u4
                mcc:
                  type: string
                  x-stoplight:
                    id: 6rfgwsgej7e8o
      description: Decision Approval for Credit Transaction Authorization
  /credit/legacy/setLimit:
    put:
      summary: Set Credit Limit
      responses:
        '200':
          $ref: '#/components/responses/LegacySetLimit'
      operationId: credit-legacy-setLimit
      x-internal: true
      description: Allow an UNDERWRITER to manually set the Credit Limit on a Company
      tags:
        - Legacy
      requestBody:
        $ref: '#/components/requestBodies/LegacySetLimit'
      x-stoplight:
        id: upf5l7e4spt7y
components:
  schemas:
    LegacySetLimit:
      title: LegacySetLimit
      x-stoplight:
        id: k8r09ytkjm1l3
      type: object
      properties:
        userId:
          type: string
          x-stoplight:
            id: p3bv28symiulh
          format: uuid
        companyId:
          type: string
          x-stoplight:
            id: d27rxgr0k1hab
          format: uuid
        level:
          type: integer
          x-stoplight:
            id: poe27w8olpfal
        approved:
          type: boolean
          x-stoplight:
            id: 2nios6933bicl
        maxLimit:
          type: integer
          x-stoplight:
            id: hedriycxerghu
        notes:
          type: string
          x-stoplight:
            id: 2b9zmt24setqd
      required:
        - maxLimit
        - notes
    ApiOnboardingCompany:
      title: ApiOnboardingCompany
      x-stoplight:
        id: ndr1nzgd4myn2
      type: object
      properties:
        id:
          type: string
        companyName:
          type: string
        doingBusinessAs:
          type: string
        taxId:
          type: string
        formationDate:
          type: string
        legalStructure:
          type: string
        website:
          type: string
        monthlyExpenditure:
          type: string
        phone:
          type: string
        address:
          $ref: '#/components/schemas/ApiAddress'
        owners:
          type: array
          items:
            $ref: '#/components/schemas/ApiCompanyOwner'
            x-stoplight:
              id: lzol0q1ivk9z9
        officers:
          type: array
          items:
            $ref: '#/components/schemas/ApiCompanyMemberBase'
            x-stoplight:
              id: eatwblchm0ehk
        financialInstitutions:
          type: array
          items:
            $ref: '#/components/schemas/ApiFinancialInstitution'
            x-stoplight:
              id: 5um0fmq8jhk26
        category:
          type: string
        annualRevenue:
          type: string
        averageMonthlyPayroll:
          type: string
        insuranceTypes:
          type: array
          items:
            x-stoplight:
              id: 6ggobkharo5vr
            type: string
        hasInsurance:
          type: boolean
        optedProducts:
          type: array
          items:
            $ref: '#/components/schemas/ApiOptedProduct'
            x-stoplight:
              id: 4wy8gczu8824q
        creditLimit:
          type: string
        autopay:
          $ref: '#/components/schemas/ApiCompanyAutopay'
        formationState:
          type: string
        businessPurpose:
          type: string
        cashOnHand:
          type: string
        naicsCode:
          type: string
        reinvestTreasuryInterest:
          type: boolean
        primaryPlaidAccount:
          type: string
        companySpend:
          type: string
        companyType:
          type: string
        merchantCategory:
          type: string
        createdAt:
          type: string
        createdBy:
          type: string
        frozen:
          type: boolean
        frozenReason:
          $ref: '#/components/schemas/ApiFrozenReason'
        businessVertical:
          $ref: '#/components/schemas/ApiBusinessVertical'
        requestedCreditLimit:
          type: string
        earlypay:
          $ref: '#/components/schemas/ApiEarlypay'
        cashback:
          $ref: '#/components/schemas/ApiCashback'
        activated:
          type: boolean
        requestedDocuments:
          type: array
          items:
            x-stoplight:
              id: zl1kc7jyysd07
            type: string
        riskGrade:
          type: string
        additionalInfo:
          type: object
        controlPerson:
          type: string
      required:
        - id
        - companyName
        - doingBusinessAs
        - taxId
        - formationDate
        - legalStructure
        - website
        - monthlyExpenditure
        - phone
        - address
        - owners
        - officers
        - financialInstitutions
        - category
        - annualRevenue
        - averageMonthlyPayroll
        - insuranceTypes
        - hasInsurance
        - optedProducts
        - autopay
        - formationState
        - businessPurpose
        - cashOnHand
        - naicsCode
        - reinvestTreasuryInterest
        - primaryPlaidAccount
        - companySpend
        - companyType
        - merchantCategory
        - createdBy
        - requestedCreditLimit
        - earlypay
        - cashback
        - activated
        - requestedDocuments
    ApiCompanyMemberBase:
      title: ApiCompanyMemberBase
      x-stoplight:
        id: 8pf8ainy2slw8
      type: object
      properties:
        id:
          type: string
        address:
          type: string
        addressLine2:
          type: string
        asOf:
          type: string
        authorizedSignatory:
          type: boolean
        byUser:
          type: string
        cellPhone:
          type: string
        city:
          type: string
        companyId:
          type: string
        completedInviteNewUsers:
          type: boolean
        completedOffboarding:
          type: boolean
        completedOnboarding:
          type: boolean
        country:
          type: string
        displayName:
          type: string
        email:
          type: string
        firstName:
          type: string
        jobTitle:
          type: string
        kycPassed:
          type: string
        lastName:
          type: string
        mqUserToken:
          type: string
        phone:
          type: string
        postalCode:
          type: string
        profileDocId:
          type: string
        pushNotifTokens:
          type: string
        roles:
          type: array
          items:
            x-stoplight:
              id: 15jm76iv3ob8f
            type: string
        state:
          type: string
        status:
          type: string
        stpCardholderId:
          type: string
        stpPersonId:
          type: string
        username:
          type: string
        version:
          type: number
        tenantId:
          type: string
      required:
        - id
        - address
        - addressLine2
        - asOf
        - authorizedSignatory
        - byUser
        - cellPhone
        - city
        - companyId
        - completedInviteNewUsers
        - completedOffboarding
        - completedOnboarding
        - country
        - displayName
        - email
        - firstName
        - jobTitle
        - lastName
        - mqUserToken
        - phone
        - postalCode
        - profileDocId
        - pushNotifTokens
        - roles
        - state
        - status
        - stpCardholderId
        - stpPersonId
        - username
        - version
        - tenantId
    ApiCompanyOwner:
      title: ApiCompanyOwner
      x-stoplight:
        id: 05ixzylg4ya8q
      allOf:
        - $ref: '#/components/schemas/ApiCompanyMemberBase'
        - type: object
          x-stoplight:
            id: gzz1fsk6zmdqv
          properties:
            ownershipPct:
              type: number
              x-stoplight:
                id: tv9t2bgg9xukx
          required:
            - ownershipPct
    ApiAddress:
      title: ApiAddress
      x-stoplight:
        id: q4qyhm62ncjqm
      type: object
      properties:
        line1:
          type: string
          x-stoplight:
            id: qytv3ztxerfk0
        line2:
          type: string
          x-stoplight:
            id: g8d8zjy2obtls
        city:
          type: string
          x-stoplight:
            id: 1d2xs5rkqygj1
        state:
          type: string
          x-stoplight:
            id: 78c43l5borvnr
        postalCode:
          type: string
          x-stoplight:
            id: sgwwfqgl44jix
        country:
          type: string
          x-stoplight:
            id: b4fpsp62d2miz
      required:
        - line1
        - city
        - state
        - postalCode
    ApiFinancialInstitution:
      title: ApiFinancialInstitution
      x-stoplight:
        id: 0fkknogf2asv3
      type: object
      properties:
        id:
          type: string
        last4:
          type: string
        active:
          type: boolean
        itemId:
          type: string
        userId:
          type: string
        account:
          type: string
        logoUrl:
          type: string
        routing:
          type: string
        bankName:
          type: string
        unlinked:
          type: boolean
        accountId:
          type: string
        companyId:
          type: string
        ownerInfo:
          $ref: '#/components/schemas/ApiFinancialInstitutionOwner'
        accessToken:
          type: string
        accountName:
          type: string
        accountType:
          type: string
        officialName:
          type: string
        institutionId:
          type: string
        unitProcessorToken:
          type: string
        stripeBankAccountToken:
          type: string
        tenantId:
          type: string
      required:
        - id
        - last4
        - active
        - itemId
        - userId
        - account
        - routing
        - bankName
        - unlinked
        - accountId
        - companyId
        - accessToken
        - accountName
        - accountType
        - officialName
        - institutionId
        - unitProcessorToken
        - tenantId
    ApiFinancialInstitutionOwner:
      title: ApiFinancialInstitutionOwner
      x-stoplight:
        id: e4nvkpp8ls8l2
      type: object
      properties:
        name:
          type: string
          x-stoplight:
            id: jt19nvhlcnsa0
        email:
          type: string
          x-stoplight:
            id: rdkeomzod9zx5
        phone:
          type: string
          x-stoplight:
            id: 8l495lkga092k
        address:
          $ref: '#/components/schemas/ApiFinancialInstitutionAddress'
          x-stoplight:
            id: 5oadxerdfjgtn
      required:
        - name
        - email
        - phone
        - address
    ApiFinancialInstitutionAddress:
      title: ApiFinancialInstitutionAddress
      x-stoplight:
        id: absn8ih4tr7h9
      type: object
      properties:
        line1:
          type: string
          x-stoplight:
            id: xqc1u6uszww3b
        city:
          type: string
          x-stoplight:
            id: sy50zvw2iq92y
        state:
          type: string
          x-stoplight:
            id: ogvtrdctmzocb
        postalCode:
          type: string
          x-stoplight:
            id: gjdi4sjbwc2z6
        country:
          type: string
          x-stoplight:
            id: f2sf1vpv6qzhs
      required:
        - line1
        - city
        - state
        - postalCode
        - country
    ApiOptedProduct:
      title: ApiOptedProduct
      x-stoplight:
        id: 68qcr91y8y44i
      type: string
      enum:
        - BANKING
        - CREDIT
        - TREASURY
        - INTERNATIONAL_PAYMENTS
    ApiCompanyAutopay:
      title: ApiCompanyAutopay
      x-stoplight:
        id: 97n5opcxhtgpa
      type: object
      properties:
        when:
          type: string
          x-stoplight:
            id: z4115uyfvfykv
          enum:
            - due
            - utilization
        plaidTokenId:
          type: string
          x-stoplight:
            id: izv31eqn1r57a
        depositAccountId:
          type: string
          x-stoplight:
            id: tumo3aufdtgbl
        utilizationPct:
          type: number
          x-stoplight:
            id: 5yebz5igu6j0r
        payBalancePct:
          type: number
          x-stoplight:
            id: 5u7bfai3jo8q8
      required:
        - when
    ApiFrozenReason:
      title: ApiFrozenReason
      x-stoplight:
        id: nmndlq726ctmo
      type: string
      enum:
        - plaidUnlinked
        - plaidDropped
        - accountDelinquent
        - deniedBanking
        - byServicer
        - unknown
    ApiBusinessVertical:
      title: ApiBusinessVertical
      x-stoplight:
        id: 3vnf1zqlk2y15
      type: string
      enum:
        - AgricultureForestryFishingOrHunting
        - ArtsEntertainmentAndRecreation
        - BusinessSupportOrBuildingServices
        - Construction
        - DirectMarketingOrTelemarketing
        - EducationalServices
        - FinancialServicesCryptocurrency
        - FinancialServicesDebitCollectionOrConsolidation
        - FinancialServicesMoneyServicesBusinessOrCurrencyExchange
        - FinancialServicesOther
        - FinancialServicesPaydayLending
        - GamingOrGambling
        - HealthCareAndSocialAssistance
        - HospitalityAccommodationOrFoodServices
        - LegalAccountingConsultingOrComputerProgramming
        - Manufacturing
        - Mining
        - Nutraceuticals
        - PersonalCareServices
        - PublicAdministration
        - RealEstate
        - ReligiousCivicAndSocialOrganizations
        - RepairAndMaintenance
        - RetailTrade
        - TechnologyMediaOrTelecom
        - TransportationOrWarehousing
        - Utilities
        - WholesaleTrade
        - AdultEntertainmentDatingOrEscortServices
        - Cannabis
    ApiEarlypay:
      title: ApiEarlypay
      x-stoplight:
        id: 4hai32pchg27a
      type: object
      properties:
        dates:
          type: array
          x-stoplight:
            id: hvspzz1su9guj
          items:
            x-stoplight:
              id: yo9rprotwqvao
            type: number
        graceDays:
          type:
            - string
            - number
        rebateDate:
          type:
            - string
            - number
        rebatePct:
          type: string
        plaidTokenId:
          type: string
        depositAccountId:
          type: string
        rebateCounterpartyId:
          type: string
    ApiCashback:
      title: ApiCashback
      x-stoplight:
        id: ip8fj6l45uosz
      type: object
      properties:
        nearTermDays:
          type:
            - string
            - number
        nearTermPct:
          type: string
        farTermDays:
          type:
            - string
            - number
        farTermPct:
          type: string
        rebateDate:
          type:
            - string
            - number
    ApiSetLimitResponse:
      title: ApiSetLimitResponse
      x-stoplight:
        id: dl8h5uljf1yw1
      type: object
      properties:
        success:
          type: boolean
          x-stoplight:
            id: edaxc2h3jmktv
        company:
          $ref: '#/components/schemas/ApiOnboardingCompany'
          x-stoplight:
            id: b0q9m4uoy7zfe
      required:
        - success
        - company
  securitySchemes:
    token:
      type: http
      scheme: bearer
      description: Bearer token
  requestBodies:
    LegacySetLimit:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LegacySetLimit'
  responses:
    LegacySetLimit:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiSetLimitResponse'
security:
  - token: []
tags:
  - name: Credit
    description: Credit
  - name: Legacy
    description: Legacy
