openapi: 3.1.0
x-stoplight:
  id: sr7308je2t0fj
info:
  title: Events
  version: '1.0'
  license:
    url: 'https://opensource.org/licenses/MIT'
    name: MIT
  contact:
    email: dataops@flex.one
    name: Dataops
    url: 'https://www.flex.one'
  description: Endpoints for Events
  summary: Events
servers:
  - url: 'http://localhost:3000'
    description: Local
  - url: 'https://platform.flexbase.dev'
    description: Development
  - url: 'https://platform.flex.one'
    description: Production
paths:
  /events/mercoa:
    post:
      summary: Mercoa Events
      operationId: mercoa-webhook-events
      responses:
        '204':
          description: No Content
      x-internal: true
      description: Listens for mercoa events
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/GcpPubSubMessage.yaml
      tags:
        - Webhooks
        - Events
      parameters: []
      x-stoplight:
        id: tmim8075qm037
  /events/plaid/onExit:
    parameters: []
    post:
      summary: Create a Plaid On Exit Log
      tags:
        - Events
      operationId: post-plaid-onExit
      responses:
        '201':
          description: Created
      x-stoplight:
        id: g6vaz24rvw59n
      description: 'Post data returned by Plaid''s onExit callback; https://plaid.com/docs/link/web/#onexit'
      requestBody:
        description: onExit payload
        content:
          application/json:
            schema:
              type: object
              required:
                - metadata
              properties:
                error:
                  type: object
                  x-stoplight:
                    id: xfvtsa7ij6lpb
                  properties:
                    displayMessage:
                      type: string
                      x-stoplight:
                        id: p4pwfe99sduin
                    errorCode:
                      type: string
                      x-stoplight:
                        id: ndlf9au9nvfjl
                    errorMessage:
                      type: string
                      x-stoplight:
                        id: 9oixn5e6b00d5
                    errorType:
                      type: string
                      x-stoplight:
                        id: adbhqsoq05spz
                metadata:
                  type: object
                  x-stoplight:
                    id: cqyzv3m290cw3
                  required:
                    - status
                    - linkSessionId
                    - requestId
                  properties:
                    institution:
                      type: object
                      x-stoplight:
                        id: skntg6kiqdahd
                      properties:
                        institutionId:
                          type: string
                          x-stoplight:
                            id: 7queoiq0d7ql5
                        name:
                          type: string
                          x-stoplight:
                            id: 8ejpuwdp4nrz8
                    status:
                      type: string
                      x-stoplight:
                        id: tyekklbxmddgj
                    linkSessionId:
                      type: string
                      x-stoplight:
                        id: u17jtanc1fxel
                      format: uuid
                    requestId:
                      type: string
                      x-stoplight:
                        id: wr81axrtu29se
  '/events/plaid/onExit/person/{personId}':
    parameters:
      - schema:
          type: string
        name: personId
        in: path
        required: true
        description: uuid for the person/user
    get:
      summary: List Plaid On Exit Events Person
      tags:
        - Events
      operationId: list-plaid-onExit-events-by-person
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - metadata
                properties:
                  metadata:
                    $ref: ./models/PaginationMetadata.yaml
                    x-stoplight:
                      id: imaqdjx6vb9pc
                  data:
                    type: array
                    x-stoplight:
                      id: r3w2q9vqvwrdk
                    items:
                      x-stoplight:
                        id: es7gvdocyhyk6
                      type: object
                      required:
                        - personId
                        - createdAt
                        - status
                        - linkSessionId
                        - requestId
                      properties:
                        personId:
                          type: string
                          x-stoplight:
                            id: wms3oxaqjpznt
                          format: uuid
                        createdAt:
                          type: string
                          x-stoplight:
                            id: dvrypzw2cpf36
                          format: date-time
                        errorType:
                          type: string
                          x-stoplight:
                            id: cy1to4q14drh9
                        errorCode:
                          type: string
                          x-stoplight:
                            id: famyqv3wn86ko
                        errorMessage:
                          type: string
                          x-stoplight:
                            id: tduwyjvmc41zi
                        displayMessage:
                          type: string
                          x-stoplight:
                            id: k4e9m138znhhu
                        institutionName:
                          type: string
                          x-stoplight:
                            id: 1hnpwdki6mpad
                        institutionId:
                          type: string
                          x-stoplight:
                            id: mhj6uuyxeilgo
                        status:
                          type: string
                          x-stoplight:
                            id: jkjhl2e20yffa
                        linkSessionId:
                          type: string
                          x-stoplight:
                            id: npgyty66d7zot
                          format: uud
                        requestId:
                          type: string
                          x-stoplight:
                            id: 7h7n8v6yk7ctt
      x-stoplight:
        id: p3gg4utqhh262
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/sort'
        - $ref: '#/components/parameters/nextToken'
        - $ref: '#/components/parameters/pageSize'
      description: list plaid onExit events by person
components:
  schemas:
    ListMetricResult:
      title: ListMetricResult
      x-stoplight:
        id: acnv3c4xt0i44
      type: object
      description: 'For a given metric, result is a timeseries of that metric with accompanying metadata'
      properties:
        product:
          type: string
          x-stoplight:
            id: u7tbep3o65sd6
        metricKey:
          type: string
          x-stoplight:
            id: cxu72o3fnp41a
        dateAggregation:
          type: string
          x-stoplight:
            id: wuh4961dxuy3n
        history:
          type: array
          x-stoplight:
            id: lt6rv2uzv1kjb
          items:
            $ref: '#/components/schemas/MetricHistory'
            x-stoplight:
              id: 3dcm1ij5h2lxu
    MetricHistory:
      title: MetricHistory
      x-stoplight:
        id: ojv08fd54ekev
      type: object
      properties:
        date:
          type: string
          x-stoplight:
            id: hdvfgfzulyrij
          format: date
        total:
          type: number
          x-stoplight:
            id: qip1to6wxfk3o
        count:
          type: number
          x-stoplight:
            id: 9dfr064rdnoam
        sum:
          type: number
          x-stoplight:
            id: 6odufzqa794vq
        avg:
          type: number
          x-stoplight:
            id: zly8bt32yy1cn
        median:
          type: number
          x-stoplight:
            id: 90urfdrz0u32a
        min:
          type: number
          x-stoplight:
            id: orxs0a6zwg4ps
        max:
          type: number
          x-stoplight:
            id: b3xvdja5xic13
        dimensions:
          type: string
          x-stoplight:
            id: rgej047n2z13x
      description: A single element of the timeseries in a Metric Result
  responses:
    EventsMetric:
      description: Metrics data with pagination metadata
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: '#/components/schemas/ListMetricResult'
                x-stoplight:
                  id: gf0fl5z7f5f5l
              metadata:
                $ref: ./models/PaginationMetadata.yaml
                x-stoplight:
                  id: wxazdz6y5xhtn
  parameters:
    startDate:
      name: startDate
      in: query
      required: false
      schema:
        type: string
        format: date
      description: Minimum date to include in response
    endDate:
      name: endDate
      in: query
      required: false
      schema:
        type: string
        format: date
      description: Maximum date to include in response
    dateAggregation:
      name: dateAggregation
      in: query
      required: false
      schema:
        type: string
        enum:
          - year
          - quarter
          - month
          - week
          - day
          - hour
          - minute
          - second
        example: year
      description: 'Unit of aggregation data across dates (daily, weekly, etc...)'
    page:
      name: page
      in: query
      schema:
        type: integer
        minimum: 0
        default: 0
      description: Which page of results to request
    pageSize:
      name: pageSize
      in: query
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 25
        exclusiveMinimum: 0
      description: The number of resources returned per page
    sort:
      name: sort
      in: query
      schema:
        type: string
        enum:
          - asc
          - desc
        default: asc
      description: The sort order of results
    sortDesc:
      name: sort
      in: query
      schema:
        type: string
        enum:
          - asc
          - desc
        default: desc
      description: The sort order of results
    nextToken:
      name: nextToken
      in: query
      schema:
        type: string
      description: A token to retrieve the next set of results
    metricKey:
      name: metricKey
      in: query
      required: true
      schema:
        type: string
      description: Define which pre-defined metric to return; for Events/metrics endpoints
  securitySchemes:
    token:
      type: http
      scheme: bearer
      description: Bearer token
security:
  - token: []
tags:
  - name: Events
    description: Events
